// src/constants/data.js
const initialUsers = [
  {
    id: 1,
    name: "Іван Петров",
    email: "ivan.p@example.com",
    phone: "123-456-7890",
    website: "ivanpetrov.com",
  },
  {
    id: 2,
    name: "Олена Коваленко",
    email: "olena.k@example.com",
    phone: "098-765-4321",
    website: "olenakovalenko.net",
  },
  {
    id: 3,
    name: "Михайло Бондар",
    email: "mykhailo.b@example.com",
    phone: "555-111-2222",
    website: "mykhailobondar.org",
  },
  {
    id: 4,
    name: "Наталія Мельник",
    email: "natalia.m@example.com",
    phone: "777-888-9999",
    website: "nataliame.info",
  },
  {
    id: 5,
    name: "Андрій Шевченко",
    email: "andriy.s@example.com",
    phone: "333-444-5555",
    website: "andriyshev.biz",
  },
  {
    id: 6,
    name: "Ірина Ткаченко",
    email: "iryna.t@example.com",
    phone: "666-777-8888",
    website: "irynat.co",
  },
  {
    id: 7,
    name: "Олег Савченко",
    email: "oleg.s@example.com",
    phone: "111-222-3333",
    website: "olegsav.io",
  },
  {
    id: 8,
    name: "Вікторія Поліщук",
    email: "victoria.p@example.com",
    phone: "999-000-1111",
    website: "victoriap.app",
  },
  {
    id: 9,
    name: "Дмитро Кравченко",
    email: "dmytro.k@example.com",
    phone: "444-555-6666",
    website: "dmytrok.dev",
  },
  {
    id: 10,
    name: "Софія Лисенко",
    email: "sofia.l@example.com",
    phone: "222-333-4444",
    website: "sofialy.tech",
  },
];

const initialPosts = [
  {
    id: 101,
    userId: 1,
    title: "Вступ до React Hooks",
    body: "React Hooks дозволяють використовувати стан та інші можливості React без написання класів.",
  },
  {
    id: 102,
    userId: 2,
    title: "Основи CSS Grid",
    body: "CSS Grid - це потужний інструмент для створення двовимірних макетів у веб-дизайні.",
  },
  {
    id: 103,
    userId: 1,
    title: "Асинхронний JavaScript",
    body: "Розуміння Promise, async/await є ключовим для сучасної веб-розробки.",
  },
  {
    id: 104,
    userId: 3,
    title: "Оптимізація продуктивності веб-сайтів",
    body: "Швидкість завантаження сайту впливає на користувацький досвід та SEO.",
  },
  {
    id: 105,
    userId: 4,
    title: "Вступ до Node.js",
    body: "Node.js дозволяє виконувати JavaScript на стороні сервера.",
  },
  {
    id: 106,
    userId: 5,
    title: "Що нового в ES2024?",
    body: "Огляд останніх функцій та покращень у JavaScript.",
  },
  {
    id: 107,
    userId: 6,
    title: "Розробка мобільних додатків з React Native",
    body: "Створення кросплатформних мобільних додатків за допомогою React.",
  },
  {
    id: 108,
    userId: 7,
    title: "Основи баз даних SQL",
    body: "Вступ до реляційних баз даних та мови SQL.",
  },
  {
    id: 109,
    userId: 8,
    title: "Впровадження CI/CD у вашому проекті",
    body: "Автоматизація процесів розробки та розгортання.",
  },
  {
    id: 110,
    userId: 9,
    title: "Безпека веб-додатків: поширені загрози",
    body: "Огляд основних вразливостей та методів захисту.",
  },
];

const initialComments = [
  {
    id: 201,
    postId: 101,
    name: "Анна",
    email: "anna@example.com",
    body: "Дуже корисна стаття про хуки!",
  },
  {
    id: 202,
    postId: 101,
    name: "Богдан",
    email: "bohdan@example.com",
    body: "Дякую за пояснення, тепер зрозуміліше.",
  },
  {
    id: 203,
    postId: 102,
    name: "Катерина",
    email: "kateryna@example.com",
    body: "CSS Grid дійсно спрощує макети.",
  },
  {
    id: 204,
    postId: 103,
    name: "Денис",
    email: "denys@example.com",
    body: "Чудовий огляд асинхронності.",
  },
  {
    id: 205,
    postId: 104,
    name: "Єва",
    email: "yeva@example.com",
    body: "Поради з оптимізації дуже доречні.",
  },
  {
    id: 206,
    postId: 105,
    name: "Федір",
    email: "fedir@example.com",
    body: "Цікаво, як Node.js працює з бекендом.",
  },
  {
    id: 207,
    postId: 106,
    name: "Галина",
    email: "halyna@example.com",
    body: "З нетерпінням чекаю на нові функції JS.",
  },
  {
    id: 208,
    postId: 107,
    name: "Ігор",
    email: "ihor@example.com",
    body: "React Native - це майбутнє мобільної розробки.",
  },
  {
    id: 209,
    postId: 108,
    name: "Жанна",
    email: "zhanna@example.com",
    body: "SQL завжди актуальний.",
  },
  {
    id: 210,
    postId: 109,
    name: "Костянтин",
    email: "kostya@example.com",
    body: "CI/CD значно прискорює роботу.",
  },
  {
    id: 211,
    postId: 110,
    name: "Людмила",
    email: "lyudmila@example.com",
    body: "Безпека - це пріоритет.",
  },
  {
    id: 212,
    postId: 101,
    name: "Марія",
    email: "maria@example.com",
    body: "Ще раз дякую за статтю про хуки, дуже допомогло!",
  },
  {
    id: 213,
    postId: 102,
    name: "Назар",
    email: "nazar@example.com",
    body: "Чи є якісь обмеження у CSS Grid?",
  },
  {
    id: 214,
    postId: 103,
    name: "Оксана",
    email: "oksana@example.com",
    body: "Які бібліотеки ви рекомендуєте для роботи з асинхронністю?",
  },
  {
    id: 215,
    postId: 104,
    name: "Павло",
    email: "pavlo@example.com",
    body: "Як виміряти продуктивність сайту?",
  },
];

export { initialUsers, initialPosts, initialComments };
